import { DEFAULT_MAP_CENTER as _DEFAULT_MAP_CENTER, DEFAULT_MAP_ZOOM as _DEFAULT_MAP_ZOOM } from '../../../MapConstant/'


export const DEFAULT_MAP_CENTER = _DEFAULT_MAP_CENTER
export const DEFAULT_MAP_ZOOM = _DEFAULT_MAP_ZOOM
export const DEFAULT_MAP_PROJECTION = 'EPSG:3857'// 坐标展示投影
export const DEFAULT_MAP_SOURCE_PROJECTION = 'EPSG:4326'// 坐标源投影

export const MAP_TILE_LAYER_NAME = 'MAP_TILE_LAYER'